unstable_features = true

blank_lines_upper_bound = 3
condense_wildcard_suffixes = true
match_block_trailing_comma = true

imports_granularity = "Module"
group_imports = "StdExternalCrate"

overflow_delimited_expr = true
struct_field_align_threshold = 20

wrap_comments = true
max_width = 100